version: '3.1'

services:

  app:
      build: .
      image: guilherme/notesapp:latest
      ports:
          - "8000:8000"
  db:
    image: postgres:12.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
